[package]
name = "usart"
version = "0.1.0"
authors = ["Ming Yang <my18345@alumni.bristol.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serial-unix = "0.4.0"

serial-core = "0.4.0"
